import fs from 'fs';
import path from 'path';
const distDir = path.resolve('./game/dist');
const outputFile = path.resolve('./dist/embed.js');
function collectFiles(dir, base = '') {
  const files = {};  
  const entries = fs.readdirSync(dir, { withFileTypes: true });  
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = path.posix.join(base, entry.name);
    if (entry.isDirectory()) {
      Object.assign(files, collectFiles(fullPath, relPath));    
    } else {
	      const content = fs.readFileSync(fullPath);
	      const ext = path.extname(entry.name).toLowerCase();
	      const textExtensions = ['.html', '.js', '.css', '.svg', '.json', '.txt'];
	      if (textExtensions.includes(ext)) {
	        const text = content.toString('utf8');
	        files[relPath] = {
	          type: 'text',
	          content: text,
          };
        }
        else {
	        const base64 = content.toString('base64');
	        files[relPath] = {
	          type: 'binary',
	          content: base64,
          };
        }
    }
  }
  return files;
}

const files = collectFiles(distDir);
const output =
`// Auto-generated by generate-embed.js\n` +
`export const fileServer = ` +
JSON.stringify(files, null, 2) +
`;\n`;

fs.promises.writeFile(outputFile, output)
	.then(() => console.log('Embedded files written to', outputFile))
	.catch(console.error);